name: Setup Publishing Context
description: Check if running from tag and if version is already published


inputs:
  package:
    description: NPM package name to check (e.g., '@org/package')
    required: true
  registry-url:
    description: NPM registry URL to check against
    required: true
  tag-prefix:
    description: Version tag prefix to match
    required: false
    default: 'v'

outputs:
  is-tag:
    description: 'Whether this workflow is triggered by a version tag (boolean)'
    value: ${{ steps.setup.outputs.is-tag }}
  tag-version:
    description: 'Extracted version from the tag (e.g., "1.2.3" from "v1.2.3")'
    value: ${{ steps.setup.outputs.tag-version }}
  is-published:
    description: 'Whether any version of the package exists in the registry (boolean)'
    value: ${{ steps.setup.outputs.is-published }}
  published-version:
    description: 'Latest published version found in the registry'
    value: ${{ steps.setup.outputs.published-version }}
  should-publish:
    description: 'Whether the package should be published (is tag && not already published)'
    value: ${{ steps.setup.outputs.should-publish }}
  already-published:
    description: 'Whether the current tag version is already published (boolean)'
    value: ${{ steps.setup.outputs.already-published }}

runs:
  using: composite
  steps:
    - name: Setup context
      id: setup
      uses: actions/github-script@v8
      env:
        PACKAGE: ${{ inputs.package }}
        REGISTRY_URL: ${{ inputs.registry-url }}
        TAG_PREFIX: ${{ inputs.tag-prefix }}
      with:
        script: |
          const package = process.env.PACKAGE;
          const registryUrl = process.env.REGISTRY_URL;
          const tagPrefix = process.env.TAG_PREFIX;

          // Validate inputs
          if (!package) {
            core.setFailed('Package name is required');
            return;
          }
          if (!registryUrl) {
            core.setFailed('Registry URL is required');
            return;
          }

          // Initialize context
          const ref = context.ref;
          const tagPattern = `refs/tags/${tagPrefix}`;
          const isTag = ref.startsWith(tagPattern);
          const tagVersion = isTag ? ref.replace(tagPattern, '') : '';

          // Initialize outputs
          let isPublished = false;
          let publishedVersion = '';
          let alreadyPublished = false;
          let shouldPublish = false;

          // Set basic outputs
          core.setOutput('is-tag', isTag);
          core.setOutput('tag-version', tagVersion);

          // Start building summary
          const summary = core.summary.addHeading('📦 Publishing Context', 2);

          // Add trigger information
          const triggerInfo = [
            ['Trigger', isTag ? '🏷️ Version Tag' : '🔀 Branch/PR'],
            ['Reference', `\`${ref}\``],
          ];

          if (isTag) {
            triggerInfo.push(['Tag Version', `\`${tagVersion}\``]);

            // Validate version format
            const semverRegex = /^\d+\.\d+\.\d+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+)?$/;
            if (!semverRegex.test(tagVersion)) {
              core.warning(`Tag version "${tagVersion}" doesn't match semver format`);
              summary.addRaw(`⚠️ **Warning:** Tag version doesn't match semver format\n\n`);
            }

            // Check registry for existing version
            try {
              core.info(`Checking registry for ${package}@${tagVersion}...`);

              const { exitCode, stdout, stderr } = await exec.getExecOutput(
                'bun',
                ['info', package, 'version', 'latest', '--registry', registryUrl],
                {
                  ignoreReturnCode: true,
                  silent: true
                }
              );

              if (exitCode === 0 && stdout.trim()) {
                publishedVersion = stdout.trim();
                isPublished = true;
                alreadyPublished = tagVersion === publishedVersion;
                shouldPublish = !alreadyPublished;

                core.info(`Found published version: ${publishedVersion}`);

                // Add registry information to summary
                triggerInfo.push(
                  ['Registry', `<code>${registryUrl}</code>`],
                  ['Package', `<code>${package}</code>`],
                  ['Latest Published', `<code>${publishedVeion}</code>`]
                );

              } else {
                // Package not found in registry
                shouldPublish = true;
                core.info(`Package ${package} not found in registry`);

                triggerInfo.push(
                  ['Registry', `<code>${registryUUrl}</code>`],
                  ['Package', `<code>${package}</code>`],
                  ['Latest Published', '—']
                );
              }

            } catch (error) {
              core.warning(`Failed to check registry: ${error.message}`);
              summary.addRaw(`⚠️ **Warning:** Failed to check registry\n\n`);
            }
          }

          // Add trigger information table
          summary.addTable([
            [{data: 'Property', header: true}, {data: 'Value', header: true}],
            ...triggerInfo
          ]);

          // Add status section
          summary.addBreak().addHeading('Status', 3);

          if (!isTag) {
            summary.addRaw(`ℹ️ <b>Not a version tag</b> — Publishing skipped for non-tag triggers`);
          } else if (alreadyPublished) {
            summary.addRaw(`⏭️ <b>Already Published</b> — Version \u{60}${tagVersion}\u{60} already exists in registry`);
          } else if (isPublished) {
            summary.addRaw(`✅ <b>Ready to Publish</b> — Version \u{60}${tagVersion}\u{60} will be published (current: \u{60}${publishedVersion}\u{60})`);
          } else {
            summary.addRaw(`🚀 <b>First Publish</b> — Package \u{60}${package}\u{60} will be published for the first time`);
          }

          // Add next steps hint
          if (shouldPublish) {
            summary.addBreak().addBreak();
            summary.addDetails('Next Steps',
              `To publish this package:\n\n` +
              `\u{60}\u{60}\u{60}yaml\n` +
              `- name: Publish to registry\n` +
              `  if: steps.setup-context.outputs.should-publish == 'true'\n` +
              `  run: bun publish --registry ${{ inputs.registry-url }}\n` +
              `\u{60}\u{60}\u{60}\n`
            );
          }

          // Set final outputs
          core.setOutput('is-published', isPublished);
          core.setOutput('published-version', publishedVersion);
          core.setOutput('already-published', alreadyPublished);
          core.setOutput('should-publish', shouldPublish);

          // Write summary once
          await summary.write();

          // Log outputs for debugging
          core.startGroup('📊 Publishing Context Outputs');
          console.log({
            'is-tag': isTag,
            'tag-version': tagVersion,
            'is-published': isPublished,
            'published-version': publishedVersion,
            'already-published': alreadyPublished,
            'should-publish': shouldPublish
          });
          core.endGroup();

          // Set appropriate exit message
          if (shouldPublish && isTag) {
            core.notice(`Package ${package}@${tagVersion} is ready to be published`);
          } else if (alreadyPublished) {
            core.notice(`Package ${package}@${tagVersion} is already published - skipping`);
          }
