pre-commit:
  parallel: true
  commands:
    prettier:
      run: bunx pretty-quick --staged --ignore-path .gitignore
      stage_fixed: true
    lint:
      glob: "*.ts"
      run: bun typecheck
      stage_fixed: true
