banner: |
  /**
    * Copyright © 2025 kjanat
    * All Rights Reserved.
    *
    * Just testing out:
    * https://bun.sh/docs/bundler#banner
    *     and
    * https://bun.sh/docs/bundler#footer
    */
footer: |
  /** Yo mama so fat!
    * Yo' crazy! */
